export { AuthProvider } from "./contexts/AuthContext";
export { useAuth } from "./hooks/useAuth";
export { hasPermission, hasAnyPermission, hasAllPermissions } from "./permissions/permissions";
export { ROLE_PERMISSIONS, ROLE_LABELS, PERMISSION_LABELS } from "./config/rolePermissions";
export { SCREEN_PERMISSIONS, getRequiredPermission, hasReportsAccess, hasReportsExport, canAccessScreen } from "./config/screenPermissions";
export { REPORTS_VIEW_PERMISSIONS, REPORTS_EXPORT_PERMISSIONS } from "./config/rolePermissions";
export { resolveDataScope, buildScopeContext, buildScopeQueryParams, SCOPED_MODULES } from "./scope";
export type { DataScope, ScopeContext, ScopedModule } from "./scope";
export { DEMO_ACCOUNTS, DEMO_PASSWORD } from "./mockUsers";
export type { Role, Permission, AuthUser, UserStatus, AuthContextValue } from "./types";
